In [214]:
import pandas as pd
from pathlib import Path
def insert_name(name):
    # 为csv文件添加文件名列
    df_temp = pd.read_csv(name, encoding="ANSI")
    df_temp.insert(0, "文件名", name.stem)
    df_temp.iloc[:,:]=df_temp.iloc[:,:].astype("string")
     #df_temp.iloc[:,:]=df_temp.iloc[:,:].astype("string")
    for i in range(len(list(df_temp.columns))):
        
        df_temp.iloc[:,i]=df_temp.iloc[:,i].str.strip()
       
        #df_temp.iloc[:,7:8]=df_temp.iloc[:,:].astype("string")
    

    return df_temp
# 合并csv文件
hb=[]
for index,name in enumerate(Path(r'C:\Users\23934\Desktop\彩神\过程\彩神\427\5111057420220424163132').glob("*交易*.csv")):
    
    df=insert_name(name)
    hb.append(df)
data=pd.concat(hb)
data.columns=data.columns.str.strip()
data['交易金额'] = pd.to_numeric(data['交易金额'],errors='coerce')
data['交易余额'] = pd.to_numeric(data['交易余额'],errors='coerce')
#data.to_excel(r'C:\Users\23934\Desktop\彩神\重新分析2-4\427.xlsx',index=False)

In [124]:
#df.loc[df['columnName']=='the value'] 以上这篇根据DataFrame某一列的值来选择具体的某一行方法

In [212]:
#开户信息
import pandas as pd
from pathlib import Path
import re
def insert_name(name):
    # 为csv文件添加文件名列
    df_temp = pd.read_csv(name, encoding="ANSI")
    df_temp.insert(0, "文件名", name.stem)
    df_temp.iloc[:,:]=df_temp.iloc[:,:].astype("string")
     #df_temp.iloc[:,:]=df_temp.iloc[:,:].astype("string")
    for i in range(len(list(df_temp.columns))):
        
        df_temp.iloc[:,i]=df_temp.iloc[:,i].str.strip()
       
        #df_temp.iloc[:,7:8]=df_temp.iloc[:,:].astype("string")    
    return df_temp
# 合并csv文件
hb=[]
for index,name in enumerate(Path(r'C:\Users\23934\Desktop\彩神\过程\彩神\427\5111057420220424163132').glob("*[!子]账户*.csv")):
    
    df=insert_name(name)
    hb.append(df)
data_kaihu=pd.concat(hb)
data_kaihu.columns=data_kaihu.columns.str.strip()
data_kh_qka=data_kaihu.copy(deep=True)
#data_kaihu['交易卡号']=data_kaihu['交易卡号'].apply(lambda x:x[0])
#data_kaihu.to_excel(r'C:\Users\23934\Desktop\彩神\小苏\lx\427赌客与收款卡开户信息lx.xlsx',sheet_name="data_kaihu",index=False)
data_kh_qka['交易卡号']=data_kh_qka['交易卡号'].apply(lambda x:re.split(r'_', x)).apply(lambda x:x[0])
#data_kh_qka.iloc[:,4]=data_kh_qka.iloc[:,4].apply(lambda x:re.split(r'_', x)).apply(lambda x:x[0])
data_kh_qka['交易账号']=data_kh_qka['交易账号'].apply(lambda x:re.split(r'_', x)).apply(lambda x:x[0])
data_kh_qka=data_kh_qka.drop_duplicates()
with pd.ExcelWriter(r"C:\Users\23934\Desktop\彩神\重新分析2-4\427开户信息.xlsx") as writer:
     data_kaihu.to_excel(writer, sheet_name="data_kaihu",index=False)  
    data_kh_qka.to_excel(writer, sheet_name="data_kh_qka",index=False)

In [215]:
data

,文件名,交易卡号,交易账号,查询反馈结果原因,交易户名,交易证件号码,交易时间,交易金额,交易余额,收付标志,...,对手交易余额,交易流水号,日志号,凭证种类,凭证号,交易柜员号,备注,商户名称,商户代码,交易类型
0,上海农村商业银行股份有限公司交易明细信息,6231626031033503198,79931000225147668,成功,,,2022-01-01 00:00:00,200.0,200.04,进,...,,1150720,,,,,,,,提现/付款
1,上海农村商业银行股份有限公司交易明细信息,6231626031033503198,79931000225147668,成功,,,2022-01-01 00:00:00,18.0,182.04,出,...,,4343232,,,0,,,,,支付宝支付
2,上海农村商业银行股份有限公司交易明细信息,6231626031033503198,79931000225147668,成功,,,2022-01-01 00:00:00,30.0,152.04,出,...,,4764067,,,0,,,,,支付宝支付
3,上海农村商业银行股份有限公司交易明细信息,6231626031033503198,79931000225147668,成功,,,2022-01-01 00:00:00,9.8,142.24,出,...,,4764882,,,,,,,,支付宝支付
4,上海农村商业银行股份有限公司交易明细信息,6231626031033503198,79931000225147668,成功,,,2022-01-02 00:00:00,10.0,132.24,出,...,,178195,,,,,,,,微信支付
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,长沙银行股份有限公司交易明细信息,,11000212914500000002,成功,,,2022-04-17 16:30:45,7050.0,7050.23,进,...,,990190201290282,,,,9901902,手机银行转账,,,CW
72,长沙银行股份有限公司交易明细信息,,11000212914500000002,成功,,,2022-04-10 13:26:46,100.0,0.24,出,...,,990181508820244,,,,9901815,微信零钱充值账户-快捷充值,微信零钱充值账户-快捷充值,,0159
73,长沙银行股份有限公司交易明细信息,,11000212914500000002,成功,,,2022-04-10 13:26:14,400.0,100.24,出,...,,990181508818536,,,,9901815,微信转账-微信转账,微信转账-微信转账,,0159
74,长沙银行股份有限公司交易明细信息,,11000212914500000002,成功,,,2022-04-10 13:25:45,500.0,500.24,进,...,,990181508817057,,,,9901815,肖浩支付宝转账-肖浩支付宝转账,肖浩支付宝转账-肖浩支付宝转账,,0167
75,长沙银行股份有限公司交易明细信息,,11000212914500000002,成功,,,2022-01-13 15:12:28,5.0,5.90,出,...,,990181506843456,,,,9901815,娄底智慧停车,娄底智慧停车,,0159

In [252]:
data_bank=data_kh_qka[['交易卡号','交易账号']]
data_bank=data_bank.drop_duplicates()
data_bank

                   交易卡号                  交易账号
0   6231626031033503198     32181370001904620
1   6231626031033503198     79931000652640465
2   6231626031033503198     79931000830460604
0      6217923070815344  60040066601500122144
1      6217922158136466  70070066601100188050
..                  ...                   ...
2   6230910299077583940       101017345873612
0      6210134947962593     81010000744229946
0   6230901818135181719   6230901818135181719
0                     -   6217796630002106858
0   6214467873201170997   6214467873201170997

[211 rows x 2 columns]

In [259]:
bank_dit={k:v for k,v in zip(data_bank['交易账号'],data_bank['交易卡号'])}
for k,v in bank_dit.items():
     if len(v)< 14:
        print(k,v)
        #bank_dit[k]=k
#keys=list(bank_dit.keys())
#bank_dit['6217796630002106858']='6217796630002106858'
#bank_dit

6217796630002106858 -

In [254]:
data_myzh=data[data['交易卡号']=='']['交易账号'].drop_duplicates()
for i in data_myzh:
    if i not in bank_dit.keys():
        print(i)

11000212914500000002

In [ ]:
#data_unijyzh=list(data_kh_qka['交易账号'].drop_duplicates())
def getContinent(x,y):
    if y=='':
        if x in list(filter(lambda zh: zh in bank_dit, bank_dit.keys())):
        #print(x)
        
            val=x.replace(x, bank_dit[x])
        else:
            
            val=y
    
    else:
        val=y
    
    return val

data['Value'] = data.apply(lambda row: getContinent(row['交易账号'], row['交易卡号']), axis=1)
#data[data['交易卡号']==''][['交易账号','交易卡号','Value']].iloc[2534:3639]
data.to_excel(r'C:\Users\23934\Desktop\彩神\过程\彩神\427\731.xlsx', sheet_name="data_bj",index=False)

In [255]:
df=data.copy()

df.columns

Index(['文件名', '交易卡号', '交易账号', '查询反馈结果原因', '交易户名', '交易证件号码', '交易时间', '交易金额',
       '交易余额', '收付标志', '交易对手账卡号', '现金标志', '对手户名', '对手身份证号', '对手开户银行', '摘要说明',
       '交易币种', '交易网点名称', '交易发生地', '交易是否成功', '传票号', 'IP地址', 'MAC地址', '对手交易余额',
       '交易流水号', '日志号', '凭证种类', '凭证号', '交易柜员号', '备注', '商户名称', '商户代码', '交易类型',
       'Value'],
      dtype='object')

In [257]:
# data['City'] = data['交易账号'].replace(bank_dit,regex=True)
# data['City']

In [258]:
# data[data['交易卡号']==''][['交易卡号','交易账号','City']].iloc[7000:8088]

In [256]:
#df['change_value'] = df.loc[:,2].replace(bank_dit)
#df.loc[:,1] = df.loc[:,2].map(bank_dit)
# df['City'] = df['交易帐号'].replace(bank_dit,regex=True)
# df